image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - notify

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y && apt-get install git -y )'
  - 'which ssh-agent || (apk add --no-cache openssh-client)'
  - apk add --no-cache openssh-client bash python3 docker-compose curl
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - echo "$PRIVATE_KEY" | ssh-add - > ~/.ssh/id_rsa
  - echo "StrictHostKeyChecking no" >> ~/.ssh/config
  - chmod -R 700 ~/.ssh
  - export IMAGE=$CI_REGISTRY_IMAGE

notify:
  stage: notify
  script:
    - bash ci-notify.sh "Good work"
  tags:
    - dev
  only:
    - master

notify_error:
  stage: notify
  script:
    - bash ci-notify.sh "Error work"
  when: on_failure
  tags:
    - dev
  only:
    - master