version: '3'

services:
  app:
    container_name: social-network
    image: book-review-site
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 8086:8086
    networks:
      - default
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/social-network
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: social-network
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    networks:
      - default

volumes:
  db: