version: '3'

services:
  app:
    container_name: social-network
    image: book-review-site
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 8086:8080
    networks:
      - default
    environment:
      DB_HOST: postgres
      DB_URL: jdbc:postgresql://postgres:5432/social-network
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: social-network
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    networks:
      - default
  grafana:
    build: './config/grafana'
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus

networks:
  monitoring:

volumes:
  db: