version: '3'

services:
  app:
    container_name: social-network
    image: danilponos/social-network:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 8086:8080
    networks:
      - default
    environment:
      DB_HOST: postgres
      DB_URL: jdbc:postgresql://postgres:5432/social-network
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: social-network
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    networks:
      - default
  loki:
    image: grafana/loki:2.5.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - /var/log:/var/log
    command:  -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki

networks:
  loki:

volumes:
  db:
